/* Native Canvas and pure-state QA. No browser or network is used. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {createCanvas,Path2D,DOMMatrix,ImageData,GlobalFonts}=require('@napi-rs/canvas');
global.window=global;Object.assign(global,{Path2D,DOMMatrix,ImageData,document:{createElement:()=>createCanvas(1920,1080)}});
const root=path.resolve(__dirname,'..');for(const n of['rich-song','rich-lib','rich-cast'])require(root+'/vendor/'+n+'.js');
GlobalFonts.registerFromPath(root+'/assets/ZCOOLKuaiLe-Regular.ttf','KuaiLe');GlobalFonts.registerFromPath(root+'/assets/Fredoka-Variable.ttf','Fredoka');
(async()=>{
 const clock=await import(root+'/src/music-clock.mjs');assert.equal(clock.musicTime(5),5);clock.withMusicClock(10,11,()=>{assert.equal(clock.musicTime(5),6);clock.withMusicClock(8,12,()=>assert.equal(clock.musicTime(5),9));assert.equal(clock.musicTime(5),6);});assert.equal(clock.musicTime(5),5);try{clock.withMusicClock(4,9,()=>{throw Error('restore test')})}catch{}assert.equal(clock.musicTime(5),5);
 const A=await import(root+'/src/blocks/a-opening-pelican.mjs'),B=await import(root+'/src/blocks/b-game-overload.mjs'),M=await import(root+'/src/action-motion.mjs');
 const original=path.resolve(root,'../miniature_preview/input/unpacked/src/blocks');
 const oldA=await import(original+'/a-opening-pelican.mjs'),oldB=await import(original+'/b-game-overload.mjs');
 assert.deepEqual(A.SHOTS,oldA.SHOTS,'A source cuts unchanged');assert.deepEqual(B.SHOTS,oldB.SHOTS,'B source cuts unchanged');
 let states=0,anchorChecks=0;
 const finite=(o,p='state')=>{if(typeof o==='number')assert(Number.isFinite(o),p);else if(o&&typeof o==='object')for(const[k,v]of Object.entries(o))finite(v,p+'.'+k)};
 for(let f=540;f<2160;f++){const m=f<1080?A:B,s=m.stateAt(f/30);finite(s);assert.deepEqual(s,m.stateAt(f/30),'deterministic');states++;}
 const distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const intersects=(a,b,c,d)=>cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0;
 for(const [t,hand]of[[44.2,'head'],[46.02,'rHand'],[59.355,'rHand'],[65.1666666667,'rHand'],[68.9,'rHand']]){assert(distance(B.stateAt(t).anchors[hand],oldB.stateAt(t).anchors[hand])<1e-7,'authored contact anchor '+t);anchorChecks++;}
 for(const t of[28.1,29.1,30.1,32.99,33.15]){let s=A.stateAt(t),old=oldA.stateAt(t);if(s.grip){const hand=s.grip==='saddle'?'rHand':'lHand';assert(distance(s.anchors[hand],old.anchors[hand])<1e-7,'bicycle grip '+t);anchorChecks++;}}
 for(const [t,name]of[[22.6666666667,'frame'],[23.6333333333,'rear'],[24.5666666667,'front']])assert.equal(A.stateAt(t).bicycle.assembly[name],1,'seated assembly '+name);const pelican=A.stateAt(26.4333333333).bicycle;assert.equal(pelican.birdLift,0,'pelican meets saddle');for(let i=0;i<2;i++)assert(distance(pelican.legs[i].foot,pelican.pedals[i])<1e-8,'pelican foot stays on pedal');for(const t of[28,29,30,32.7,33.1,34]){const b=A.stateAt(t).bicycle;assert(Math.abs(b.wheelAngle*b.scale*68-b.travel)<1e-8,'rolling contact no-slip');assert(Math.abs(b.crankAngle*1.8-b.wheelAngle)<1e-8,'chain gear ratio retained');}
 for(const t of[23.3,23.7,24.2,24.40,24.5666666667,24.6,24.7,24.79]){const s=A.stateAt(t);assert(distance(s.wrench.jaw,s.wrench.axle)<1e-8,'wrench jaw sits on axle');assert(distance(s.anchors.rHand,s.wrench.grip)<1e-8,'right paw grasps wrench handle');assert(distance(s.anchors.lHand,s.wrench.axle)<1e-8,'left paw supports axle');assert(s.anchors.lHand[0]<s.anchors.rHand[0],'hands remain ordered');for(const a of[[s.rig.l.S,s.rig.l.E],[s.rig.l.E,s.rig.l.C]])for(const b of[[s.rig.r.S,s.rig.r.E],[s.rig.r.E,s.rig.r.C]])assert(!intersects(...a,...b),'wrench pose arms do not cross');}
 const catchState=B.stateAt(46.02);assert.equal(catchState.coin.phase,'caught-hold');assert.equal(catchState.coin.scale,1);assert(distance([catchState.coin.x,catchState.coin.y],[catchState.anchors.rHand[0]+3,catchState.anchors.rHand[1]-16])<1e-9);
 const basin=B.stateAt(59.355);assert(Math.abs(basin.fallingCard.bottom-basin.basin.top)<1e-9,'card touches basin crest');assert.equal(basin.fallingCard.phase,'contact-hold');
 const hit=65.1666666667,stamp=[];for(const dt of[0,.02,.04,.07,.10,.14,.16]){const s=B.stateAt(hit+dt);assert(Math.abs(s.stampGeometry.baseY-s.stampGeometry.contactY)<1e-7,'compressed rubber remains on contact plane');stamp.push({dt,compression:s.stampCompression,baseY:s.stampGeometry.baseY});}assert(B.stateAt(hit+.32).stampGeometry.baseY<756.32-20,'stamp rebounds');
 const phases=[68.8,69.15,69.5,69.9,70.3].map(t=>({t,...B.codeCollapseState(t,1,true)}));assert(phases[1].rows.slice(0,3).every(r=>r.fall>.6));assert(phases[1].rows.slice(3).every(r=>r.fall===0));assert(phases[2].rows.slice(7).every(r=>r.fall===0));assert(phases[4].rows.every(r=>r.fall===1));
 assert(Math.abs(M.beatWave(60,2)-M.beatWave(60+2*M.BEAT,2))<1e-12,'musical loops repeat every two beats');
 const out=root+'/qa';fs.mkdirSync(out,{recursive:true});
 const times=[22.67,23.70,24.5666666667,24.64,26.4333333333,26.59,29.45,33.1,35.8,44.2,46.02,46.12,59.355,59.45,65.1666666667,65.2366666667,65.56,68.92,69.15,69.48,69.88,70.18];
 const sheet=createCanvas(1920,Math.ceil(times.length/3)*360),sg=sheet.getContext('2d');sg.fillStyle='#082653';sg.fillRect(0,0,sheet.width,sheet.height);
 const canvas=createCanvas(1920,1080),g=canvas.getContext('2d');const files=[];
 for(const[t,n]of times.map((t,n)=>[t,n])){(t<36?A:B).renderFrame(g,t);const pix=g.getImageData(0,0,1920,1080).data;let opaque=0;for(let j=3;j<pix.length;j+=4)if(pix[j]>0)opaque++;assert(opaque>1920*1080*.99,'opaque complete native frame');const x=(n%3)*640,y=Math.floor(n/3)*360;sg.drawImage(canvas,x,y,640,360);sg.fillStyle='#082653';sg.fillRect(x,y,172,29);sg.fillStyle='#ffe3a0';sg.font='19px sans-serif';sg.fillText('Source '+t.toFixed(3)+'s',x+8,y+21);if([24.5666666667,46.02,59.355,65.2366666667,69.48,69.88].includes(t)){const file=out+'/action-'+t.toFixed(3).replace('.','-')+'.png';fs.writeFileSync(file,canvas.toBuffer('image/png'));files.push(path.basename(file));}}
 fs.writeFileSync(out+'/action-contact-sheet.jpg',sheet.toBuffer('image/jpeg',88));
 const report={ok:true,nativeFramesRendered:times.length,pureStatesChecked:states,determinismChecks:states,baselineContactAnchorsUnchanged:anchorChecks,sourceCutArraysUnchanged:true,wheelSeatAndPedalContacts:true,wrenchJawAndHandContacts:true,rollingAndChainRatios:true,scopedMusicClockRestoration:true,coinCatch:{at:46.02,heldUntil:46.2,center:[catchState.coin.x,catchState.coin.y],paw:catchState.anchors.rHand},basinContact:{at:59.355,cardBottom:basin.fallingCard.bottom,basinTop:basin.basin.top},stampCompression:stamp,collapseStages:phases.map(s=>({t:s.t,phase:s.phase,progress:s.rows.map(r=>r.fall)})),gaitBeatsPerStride:2,renderFiles:files,contactSheet:'action-contact-sheet.jpg',browserTested:false};
 fs.writeFileSync(out+'/action-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
