/* Offline player checks. This uses a deterministic DOM/media model, not a browser. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),{spawnSync}=require('child_process');
if(!vm.SourceTextModule){const child=spawnSync(process.execPath,['--experimental-vm-modules',__filename,...process.argv.slice(2)],{stdio:'inherit'});process.exit(child.status??1)}
const root=path.resolve(__dirname,'..'),final=process.argv.includes('--final'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=p=>fs.readFileSync(path.join(root,p)),checks=[],failures=[];
async function check(name,fn){try{const detail=await fn();checks.push({name,passed:true,...(detail?{detail}:{})})}catch(e){checks.push({name,passed:false,error:e.message});failures.push(name+': '+e.message)}}
class Events{constructor(){this.listeners=new Map()}addEventListener(name,fn,opts={}){const list=this.listeners.get(name)||[];list.push({fn,once:opts.once});this.listeners.set(name,list)}emit(name){for(const e of [...(this.listeners.get(name)||[])]){if(e.once)this.listeners.set(name,this.listeners.get(name).filter(x=>x!==e));e.fn({type:name})}this['on'+name]?.({type:name})}}
class Audio extends Events{constructor(){super();this.currentTime=0;this.readyState=4;this.paused=true;this.playCalls=0;this.pauseCalls=0;this.pending=[];this.defer=false;this.nextError=null}play(){this.playCalls++;if(this.nextError){const e=this.nextError;this.nextError=null;return Promise.reject(e)}this.paused=false;if(!this.defer)return Promise.resolve();return new Promise((resolve,reject)=>this.pending.push({resolve,reject}))}pause(){this.pauseCalls++;this.paused=true;for(const p of this.pending.splice(0))p.reject(new Error('The play request was interrupted by pause'))}resolvePlay(){for(const p of this.pending.splice(0))p.resolve()}}
const settle=async()=>{for(let n=0;n<10;n++)await Promise.resolve()};
async function harness(options={}){const audio=new Audio();Object.assign(audio,options);const frames=[],raf=new Map(),fonts=[],window=new Events(),document=new Events();let next=0;const elements={stage:{getContext:()=>({})},audio,seek:{value:0},time:{},play:{disabled:true},pause:{disabled:true},replay:{disabled:true},status:{}};document.getElementById=id=>elements[id];document.hidden=false;document.fonts={load:async (...a)=>fonts.push(a),ready:Promise.resolve()};const context={window,document,performance:{now:()=>Date.now()},console:{info:()=>{}},requestAnimationFrame:fn=>{raf.set(++next,fn);return next},cancelAnimationFrame:id=>raf.delete(id),renderFrame:(_,t)=>frames.push(t),DURATION:140.032,SHOTS:[{start:0,end:140.032,id:'test'}]};const code=read('src/player.mjs').toString().replace(/^import[^\n]+\n/,'');await vm.runInNewContext('(async()=>{'+code+'\n})()',context);return{audio,window,document,e:elements,raf,frames,fonts,debug:()=>window.__sampleDebug(),click:async id=>{elements[id].onclick();await settle()},tick:async t=>{audio.currentTime=t;const f=[...raf.values()];raf.clear();for(const x of f)x();await settle()}}}
async function controls(){
await check('Initialization renders frame zero and loads both embedded font families',async()=>{const h=await harness();assert.equal(h.frames[0],0);assert.equal(h.e.status.textContent,'已就绪');assert.equal(h.e.play.disabled,false);assert.equal(h.e.replay.disabled,false);assert.equal(h.fonts.length,2)});
await check('Play/repeated play creates one audio start and one animation loop',async()=>{const h=await harness();await h.click('play');for(let n=0;n<20;n++)h.e.play.onclick();await settle();assert.equal(h.audio.playCalls,1);assert.equal(h.raf.size,1);assert.equal(h.debug().playing,true);await h.tick(1.234);assert.equal(h.debug().rendered,1.234);assert.equal(h.raf.size,1)});
await check('Pause cancels animation and restores controls',async()=>{const h=await harness();await h.click('play');await h.click('pause');assert.equal(h.raf.size,0);assert.equal(h.audio.paused,true);assert.equal(h.debug().playing,false);assert.equal(h.e.play.disabled,false);assert.equal(h.e.pause.disabled,true)});
await check('Seek while paused and playing follows audio clock without extra loops',async()=>{const h=await harness();h.e.seek.value='42.5';h.e.seek.oninput();assert.equal(h.audio.currentTime,42.5);assert.equal(h.debug().rendered,42.5);assert.equal(h.raf.size,0);await h.click('play');h.e.seek.value='93.5';h.e.seek.oninput();h.audio.emit('seeked');assert.equal(h.debug().rendered,93.5);assert.equal(h.raf.size,1)});
await check('Replay and rapid replay restart once without stacking animation loops',async()=>{const h=await harness();await h.click('play');await h.tick(54);for(let n=0;n<20;n++)h.e.replay.onclick();await settle();assert.equal(h.audio.currentTime,0);assert.equal(h.audio.playCalls,2);assert.equal(h.raf.size,1);assert.equal(h.debug().playing,true)});
await check('Natural end and timeline end stop at the final frame; play starts again',async()=>{const h=await harness();await h.click('play');await h.tick(140.03);assert.equal(h.debug().playing,false);assert.equal(h.raf.size,0);assert.equal(h.debug().rendered,140.031);assert.equal(h.e.status.textContent,'全片播放结束');await h.click('play');assert.equal(h.audio.currentTime,0);h.audio.emit('ended');assert.equal(h.debug().playing,false);assert.equal(h.raf.size,0)});
await check('Hidden page and pagehide cancel playing state',async()=>{const h=await harness();await h.click('play');h.document.hidden=true;h.document.emit('visibilitychange');assert.equal(h.audio.paused,true);assert.equal(h.raf.size,0);h.document.hidden=false;await h.click('play');h.window.emit('pagehide');assert.equal(h.audio.paused,true);assert.equal(h.raf.size,0)});
await check('Rejected playback recovers on the next explicit play',async()=>{const h=await harness();h.audio.nextError=new Error('Playback was blocked');await h.click('play');assert.equal(h.e.play.disabled,false);assert.equal(h.debug().starting,false);assert.match(h.e.status.textContent,/Playback was blocked/);await h.click('play');assert.equal(h.debug().playing,true);assert.equal(h.raf.size,1)});
await check('Pause and hiding while metadata is pending cancel delayed playback',async()=>{for(const method of ['pause','hidden','pagehide']){const h=await harness({readyState:0});h.e.play.onclick();await settle();assert.equal(h.debug().starting,true);if(method==='pause')h.e.pause.onclick();if(method==='hidden'){h.document.hidden=true;h.document.emit('visibilitychange')}if(method==='pagehide')h.window.emit('pagehide');h.audio.readyState=4;h.audio.emit('loadedmetadata');await settle();assert.equal(h.audio.playCalls,0);assert.equal(h.raf.size,0);assert.equal(h.debug().playing,false)}});
await check('Pause/replay during pending play rejects stale starts and permits recovery',async()=>{const h=await harness({defer:true});h.e.play.onclick();await settle();assert.equal(h.audio.pending.length,1);h.e.pause.onclick();await settle();assert.equal(h.raf.size,0);assert.equal(h.debug().starting,false);h.e.play.onclick();await settle();h.audio.resolvePlay();await settle();assert.equal(h.debug().playing,true);assert.equal(h.raf.size,1);h.e.replay.onclick();await settle();assert.equal(h.audio.currentTime,0);assert.equal(h.debug().starting,true);h.audio.resolvePlay();await settle();assert.equal(h.debug().playing,true);assert.equal(h.raf.size,1)});
await check('Audio decode errors stop rendering and enable user retry',async()=>{const h=await harness();await h.click('play');h.audio.emit('error');await settle();assert.equal(h.audio.paused,true);assert.equal(h.raf.size,0);assert.equal(h.e.play.disabled,false);assert.match(h.e.status.textContent,/AAC/)});
}
async function bundle(){let html,scripts,sources,imports;
await check('HTML contains exactly the expected two script elements and offline CSP',()=>{html=read('output/DeepSeek-Whale-Cutpaper-Full-Film.html').toString();scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)];assert.equal(scripts.length,2);assert.match(html,/connect-src 'none'/);assert.match(html,/script-src 'unsafe-inline' blob:/);assert.match(html,/<canvas id="stage" width="1920" height="1080"/);assert.match(scripts[1][1],/type="module"/);return{htmlBytes:Buffer.byteLength(html),htmlSha256:sha(html)}});
if(!scripts)return;
await check('Every embedded source module matches current source with CRLF normalized',()=>{const code=scripts[1][2],start=code.indexOf('const sources=')+14,mid=code.indexOf(',imports='),end=code.indexOf(',urls=new Map()');assert(start>=14&&mid>start&&end>mid);sources=JSON.parse(code.slice(start,mid));imports=JSON.parse(code.slice(mid+9,end));const mismatches=[];for(const [id,src]of Object.entries(sources))if(read(id).toString().replace(/\r\n/g,'\n')!==src)mismatches.push(id);assert.deepEqual(mismatches,[]);return{moduleCount:Object.keys(sources).length,moduleHashes:Object.fromEntries(Object.entries(sources).map(([id,s])=>[id,sha(s)]))}});
if(!sources)return;
await check('All static imports parse, resolve within bundle, and link with matching exports',async()=>{const modules={};for(const[id,src]of Object.entries(sources))modules[id]=new vm.SourceTextModule(src,{identifier:id});const targets=new Set();for(const[id,module]of Object.entries(modules)){for(const specifier of module.dependencySpecifiers){assert(specifier.startsWith('.'),id+' external import '+specifier);const target=path.posix.normalize(path.posix.join(path.posix.dirname(id),specifier));assert(modules[target],id+' missing '+target);targets.add(target)}for(const link of imports[id])assert(sources[link.target],id+' missing import table target '+link.target)}await modules['src/player.mjs'].link((spec,ref)=>modules[path.posix.normalize(path.posix.join(path.posix.dirname(ref.identifier),spec))]);return{modules:Object.keys(modules).length,resolvedTargets:targets.size}});
await check('Blob URL bootstrap rewrites all imports and reaches every bundled module',()=>{let n=0;const blobs=new Map(),context={Blob:class{constructor(parts){this.text=parts.join('')}},URL:{createObjectURL:b=>{const url='blob:offline-check/'+(++n);blobs.set(url,b.text);return url}}};const code=scripts[1][2],boot=code.slice(0,code.indexOf('try{await import'));vm.runInNewContext(boot+";globalThis.entry=url('src/player.mjs');",context);assert.equal(blobs.size,Object.keys(sources).length);for(const[url,src]of blobs){const parsed=new vm.SourceTextModule(src,{identifier:url});for(const specifier of parsed.dependencySpecifiers)assert(blobs.has(specifier),'Unrewritten import '+specifier)}return{rewrittenModules:blobs.size}});
await check('Classic libraries match preserved source with CRLF normalized and parse',()=>{const expected=['vendor/rich-song.js','vendor/rich-lib.js','vendor/rich-cast.js'].map(p=>read(p).toString()).join('\n');assert.equal(sha(scripts[0][2]),sha(expected.replace(/\r\n/g,'\n')),'Classic library text differs beyond normalized line endings');new vm.Script(expected)});
await check('Audio and both font payloads are exact source bytes',()=>{const assets=[['assets/ZCOOLKuaiLe-Regular.ttf',/data:font\/ttf;base64,([A-Za-z0-9+/=]+)/g,0],['assets/Fredoka-Variable.ttf',/data:font\/ttf;base64,([A-Za-z0-9+/=]+)/g,1],['assets/song.m4a',/data:audio\/mp4;base64,([A-Za-z0-9+/=]+)/g,0]],result={};for(const[p,re,index]of assets){const encoded=[...html.matchAll(re)][index]?.[1];assert(encoded,'Missing '+p);const decoded=Buffer.from(encoded,'base64');assert.deepEqual(decoded,read(p));result[p]={bytes:decoded.length,sha256:sha(decoded)}}return result});
await check('Original character, cast, libraries, and soundtrack remain unchanged',()=>{const baseline=path.resolve(root,'../miniature_preview/input/unpacked'),paths=['src/paper-whale.mjs','vendor/rich-cast.js','vendor/rich-lib.js','vendor/rich-song.js','vendor/core/paper.js','vendor/core/util.js','vendor/rigs/shared.js','assets/song.m4a'];if(!fs.existsSync(baseline))return{skipped:'Original source reference is not included in this editable package'};const hashes={};for(const p of paths){assert.equal(sha(read(p)),sha(fs.readFileSync(path.join(baseline,p))),p+' changed from original');hashes[p]=sha(read(p))}return hashes});
await check('HTML has no external resource attributes, stylesheets, font URLs, or fetch calls',()=>{for(const m of html.matchAll(/\b(?:src|href)\s*=\s*["']([^"']+)["']/gi))assert(m[1].startsWith('data:')||m[1].startsWith('#'),'External resource '+m[1].slice(0,100));for(const m of [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map(x=>x[1]).join('\n').matchAll(/url\(\s*["']?([^)'"\s]+)/g))assert(m[1].startsWith('data:'),'External CSS URL '+m[1].slice(0,100));const code=[scripts[0][2],...Object.values(sources)].join('\n');assert(!/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource)\s*\(/.test(code),'Network API present')});
}
async function packageZip(){const filename='output/DeepSeek-接单喜剧-HTML与源码.zip';if(!fs.existsSync(path.join(root,filename))){if(final)await check('Final ZIP exists',()=>{throw Error('Source ZIP is missing')});return}await check('ZIP CRC, source/dependency coverage, delivered HTML, and private-file exclusions',()=>{const py=String.raw`import json,zipfile,pathlib,hashlib
root=pathlib.Path.cwd()
p=root/'output/DeepSeek-接单喜剧-HTML与源码.zip'
with zipfile.ZipFile(p) as z:
 names=z.namelist(); assert z.testzip() is None,'CRC failure'
 assert len(names)==len(set(names)),'Duplicate ZIP entries'
 bad=[n for n in names if n.startswith('/') or '..' in pathlib.PurePosixPath(n).parts or any(x in pathlib.PurePosixPath(n).parts for x in ['.git','.library_helpers','.codex','.agents','node_modules','__pycache__']) or n=='qa/subagents/verify-native.cjs']
 assert not bad,'Private or nonportable helpers: '+str(bad)
 expected=[str(p.relative_to(root)) for folder in ['src','vendor','assets'] for p in (root/folder).rglob('*') if p.is_file()]
 expected+=['README-使用说明.txt','CREDITS.md','package.json','tools/build_html.py','tools/render_film.cjs','tools/runtime.cjs','source/motion-plan-reference.md']
 missing=[n for n in expected if n not in names]; assert not missing,'Missing dependencies: '+str(missing)
 mismatch=[n for n in expected if z.read(n)!=(root/n).read_bytes()]; assert not mismatch,'Stale source: '+str(mismatch)
 html='DeepSeek-Whale-Cutpaper-Full-Film.html'; assert html in names,'Missing self-contained HTML'
 assert z.read(html)==(root/'output'/html).read_bytes(),'Stale HTML in ZIP'
 print(json.dumps({'file':p.name,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'entries':len(names),'dependencyFiles':len(expected),'crc':'pass','privateHelpers':'none','names':names}))
`;const p=spawnSync('python3',['-c',py],{cwd:root,encoding:'utf8'});assert.equal(p.status,0,p.stderr);const report=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,'qa/player-package.json'),JSON.stringify(report,null,2));return{file:report.file,bytes:report.bytes,sha256:report.sha256,entries:report.entries,dependencyFiles:report.dependencyFiles}})}
(async()=>{await controls();await bundle();await packageZip();const report={phase:final?'final':'preliminary',createdAt:new Date().toISOString(),playerSourceSha256:sha(read('src/player.mjs')),method:'Deterministic native JavaScript DOM/audio/requestAnimationFrame model plus parser/linker and byte-level bundle/package inspection',browserPlaybackVerified:false,audibleReviewVerified:false,limits:['No real browser navigation, media decode, audible playback, compositor timing, or real-browser event scheduling was tested.','Pending play interruption models standard pause rejection behavior; actual browser-specific behavior is not asserted.','The renderer is stubbed for player control tests; independent native rendering checks cover scene output.'],passed:failures.length===0,checks,failures};fs.writeFileSync(path.join(root,'qa/player-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({phase:report.phase,passed:report.passed,passedChecks:checks.filter(x=>x.passed).length,totalChecks:checks.length,failures},null,2));if(failures.length)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
